### ISSUE TITLE
Version Hash not working

### ISSUE THREAD

**Issue by bjdeng** [Archytaus/middleman-appcache#3]
THanks for building this. I'm having some trouble getting version hashing in the appcache wot work. WHen I build, middleman throws the errors below. The cache manifest still builds, but without the hash. Is there something I'm missing?

```
/Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/configuration.rb:75:in `define_setting': Setting version_hash doesn't exist (RuntimeError)
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/configuration.rb:37:in `[]='
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/configuration.rb:46:in `method_missing'
    from /Users/bjd/code/AirLifeGuidelines/slate/config.rb:36:in `block in evaluate_configuration!'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/extension.rb:367:in `setup_options'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/extension.rb:294:in `initialize'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-appcache-1.0.1/lib/middleman-appcache/extension.rb:14:in `initialize'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:64:in `new'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/extension_manager.rb:64:in `activate'
    from /Users/bjd/code/AirLifeGuidelines/slate/config.rb:33:in `evaluate_configuration!'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:301:in `instance_eval'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:301:in `evaluate_configuration!'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:277:in `start_lifecycle'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-core-4.0.0/lib/middleman-core/application.rb:265:in `initialize'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-cli-4.0.0/lib/middleman-cli/build.rb:51:in `new'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-cli-4.0.0/lib/middleman-cli/build.rb:51:in `build'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/gems/middleman-cli-4.0.0/bin/middleman:23:in `<top (required)>'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/bin/middleman:23:in `load'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/bin/middleman:23:in `<main>'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/bjd/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ryan-scott-dev** [comment]
Hi @bjdeng,

I'm sorry for taking so long to get back to you.
I hadn't published the version of this gem to rubygems where `version_hash` was introduced.

If you do a `bundle update middleman-appcache` it should be resolved now :)

Thanks for reporting this, I'll re-open the issue if you are still running into issues after updating to v1.1.0

**Comment by bjdeng** [comment]
Works like a charm now. I hadn't thought to check my local gem file, and was really scratching my head as to why this isn't working reading the source here.
